### ISSUE TITLE
7.5 As a general user Redistribute votes to other candidates using sliders See how an election would have changed if these candidates had gotten those votes instead

### ISSUE THREAD

**Issue by senseisub** [sltimmins/DB-GUI-Team-1#54]
Size: 34

Given that a user wants to redistribute votes to a particular candidate, when set a position on the slider, that percentage of the votes in the "pool" are given to that candidate instead 

Given that the sum of all the sliders equals 100%, when the user tries to change the sliders such that the sum is greater than 100%, the sliders will not increase any further unless one of the sliders is also decreased.

Given that a user doesn't want all the votes to go to other candidates, when the sum of all the sliders adds up to less that 100%, the excess votes are removed from the election

**Comment by wyattsaltzman** [comment]
did not complete
